### ISSUE TITLE
Consider not inheriting CMakeDeps

### ISSUE THREAD

**Issue by memsharded** [danimtb/ros2_conan_config#1]
https://github.com/danimtb/ros2_conan_config/blob/f3d1ca7e74c08638a8542a93ca493f277c5a5b49/extensions/generators/ament.py#L69

**Comment by danimtb** [comment]
Indeed, inheritance is not needed. Removed at 3da38a655e7b8c1a11055b816a74e284044cd6c3. Closing this issue
